### ISSUE TITLE
APN payload successfully delivered but device doesn't refresh?

### ISSUE THREAD

**Issue by titanism** [freswa/dovecot-xaps-daemon#39]
Hi there,

Per discussion at <https://github.com/nodemailer/wildduck/issues/711#issuecomment-2261575094> it seems that the APN payload gets successfully delivered, but the iOS device doesn't refresh mail.  The new messages aren't fetched (and it waits until the 15m interval) even though Push is enabled and properly setup with XAPPLEPUSHSERVICE support.

Is there any insight you can share as to why this doesn't work?

Thank you,

**Comment by freswa** [comment]
Have you checked the on-device settings?

**Comment by freswa** [comment]
So if Apple returns that the device received the push notification, the local apnsd has actually received the message. From that point on there can either be a broken payload, a local rate limit or a battery management limitation that causes the service to not work.

1. Broken payload: Have you patched anything (Dovecot, xapsd, xaps-plugin)? What commits do you use?
2. Local rate limit: The local apnsd doesn't willy-nilly forward all notifications. It protects the users from too much notifications by limiting them for rarely used apps.
3. Battery management limits: The local apnsd may not forward the notification if the device is on low battery. Also it can happen, that the remote push notification cannot be processed by Mail.app when the app itself has no energy budget to be called in the background. This is required, since the notification itself does not contain any information about the received message, but only the information about the inbox and the folder the message has been received on. So the actual UI message is generated by the local Mail.app itself.

My best bet is 1. To avoid 2 and 3 I'd recommend to use a device that is used daily and is not too old.

**Comment by freswa** [comment]
I've got this daemon running with the corresponding plugin and it sends me push notifications right now.

>  You mentioned Mail.app – which is desktop I believe [...]?

Nope. Don't mix up topics and App Names.

**Comment by freswa** [comment]
> Sorry, just to be really clear, your iOS device gets the push notification and refreshes the mailbox?

Yes.

**Comment by freswa** [comment]
Was about to point you to that client.go.
Afaik you can send arbitrary payloads. They don't get checked. From Apple's pov you're authenticated with your App-specific certificate. So any payload will only end up in your app code and nowhere else.

Only for *standard* notifications, there is a specified body format you have to adhere to, since the app is not woken up, but the notification goes straight to your notification center.

**Comment by freswa** [comment]
@titanism Just curious. Any particular reason why you don't use this project to send the actual notifications? It scales to hundreds of thousand of simultaneous users....

**Comment by freswa** [comment]
It should trigger when the App is closed, but that depends on what I wrote [here](https://github.com/freswa/dovecot-xaps-daemon/issues/39#issuecomment-2262449113).

**Comment by freswa** [comment]
@titanism Have you double checked the `aps-topic` in the IMAP response to the `XAPPLEPUSHSERVICE` cmd?

**Comment by freswa** [comment]
If that doesn't work, please try to use the Go implementation to rule out any phone issues.

**Comment by freswa** [comment]
> @freswa Do we need to respond with `aps-topic` value set to the one like `com.apple.mail.XServer.xxxxxxxxxxxxxxx`?

Yes, you do. Otherwise someone could trigger notifications with their certificate on your device.
